name: Build and Deploy to GitHub Pages

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - name: Install statusbar dependencies
        working-directory: 'src-tauri/tauri-plugin-statusbar'
        run: bun install
        shell: bash

      - name: Build statusbar
        working-directory: 'src-tauri/tauri-plugin-statusbar'
        run: bun run build

      - name: Install root dependencies
        run: bun install
        shell: bash

      - name: Run check
        run: bun run check

      - name: Run tests
        run: bun run test

      - name: Build site
        env:
          BASE_PATH: '/success-notebook'
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
